// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2025 Mikhail Revzin <p3.141592653589793238462643@gmail.com>
// Part of the DISK Commander project: https://github.com/Ptr314/dsk_commander
// Description: Text placeholder replacement utilities for UI strings

#pragma once

#include <QString>
#include <QCoreApplication>

inline QString replacePlaceholders(const QString& input)
{
    return QString(input)
        // 102 disk/filesystem placeholders (FilePanel context)
        .replace("{$DIRECTORY_ENTRY}", QCoreApplication::translate("FilePanel", "Directory Entry"))
        .replace("{$FILE_NAME}", QCoreApplication::translate("FilePanel", "File Name"))
        .replace("{$SIZE}", QCoreApplication::translate("FilePanel", "File Size"))
        .replace("{$BYTES}", QCoreApplication::translate("FilePanel", "byte(s)"))
        .replace("{$SIDES}", QCoreApplication::translate("FilePanel", "Sides"))
        .replace("{$TRACKS}", QCoreApplication::translate("FilePanel", "Tracks"))
        .replace("{$SECTORS}", QCoreApplication::translate("FilePanel", "sector(s)"))
        .replace("{$ATTRIBUTES}", QCoreApplication::translate("FilePanel", "Attributes"))
        .replace("{$DATE}", QCoreApplication::translate("FilePanel", "Date"))
        .replace("{$TYPE}", QCoreApplication::translate("FilePanel", "Type"))
        .replace("{$PROTECTED}", QCoreApplication::translate("FilePanel", "Protected"))
        .replace("{$YES}", QCoreApplication::translate("FilePanel", "Yes"))
        .replace("{$NO}", QCoreApplication::translate("FilePanel", "No"))
        .replace("{$TS_LIST_LOCATION}", QCoreApplication::translate("FilePanel", "T/S List Location"))
        .replace("{$TS_LIST_DATA}", QCoreApplication::translate("FilePanel", "T/S List Contents"))
        .replace("{$INCORRECT_TS_DATA}", QCoreApplication::translate("FilePanel", "Incorrect T/S data, stopping iterations"))
        .replace("{$NEXT_TS}", QCoreApplication::translate("FilePanel", "Next T/S List Location"))
        .replace("{$FILE_END_REACHED}", QCoreApplication::translate("FilePanel", "File End Reached"))
        .replace("{$FILE_DELETED}", QCoreApplication::translate("FilePanel", "The file is marked as deleted, the data below may be incorrect"))
        .replace("{$ERROR_PARSING}", QCoreApplication::translate("FilePanel", "File parsing error"))
        .replace("{$TRACK}", QCoreApplication::translate("FilePanel", "Track"))
        .replace("{$TRACK_SHORT}", QCoreApplication::translate("FilePanel", "T"))
        .replace("{$SIDE_SHORT}", QCoreApplication::translate("FilePanel", "H"))
        .replace("{$PHYSICAL_SECTOR}", QCoreApplication::translate("FilePanel", "S"))
        .replace("{$LOGICAL_SECTOR}", QCoreApplication::translate("FilePanel", "S"))
        .replace("{$PARSING_FINISHED}", QCoreApplication::translate("FilePanel", "Parsing finished"))
        .replace("{$VOLUME_ID}", QCoreApplication::translate("FilePanel", "V"))
        .replace("{$SECTOR_INDEX}", QCoreApplication::translate("FilePanel", "Index"))
        .replace("{$INDEX_MARK}", QCoreApplication::translate("FilePanel", "Index Mark"))
        .replace("{$DATA_MARK}", QCoreApplication::translate("FilePanel", "Data Mark"))
        .replace("{$DATA_FIELD}", QCoreApplication::translate("FilePanel", "Sector Data"))
        .replace("{$SECTOR_INDEX_END_OK}", QCoreApplication::translate("FilePanel", "End Mark: OK"))
        .replace("{$SECTOR_INDEX_END_ERROR}", QCoreApplication::translate("FilePanel", "End Mark: Not Detected"))
        .replace("{$SECTOR_CRC_OK}", QCoreApplication::translate("FilePanel", "CRC: OK"))
        .replace("{$SECTOR_CRC_ERROR}", QCoreApplication::translate("FilePanel", "CRC: Error"))
        .replace("{$CRC_EXPECTED}", QCoreApplication::translate("FilePanel", "Expected"))
        .replace("{$CRC_FOUND}", QCoreApplication::translate("FilePanel", "Found"))
        .replace("{$SECTOR_ERROR}", QCoreApplication::translate("FilePanel", "Data Error"))
        .replace("{$INDEX_CRC_OK}", QCoreApplication::translate("FilePanel", "CRC: OK"))
        .replace("{$INDEX_CRC_ERROR}", QCoreApplication::translate("FilePanel", "CRC: Error"))
        .replace("{$INDEX_EPILOGUE_OK}", QCoreApplication::translate("FilePanel", "Epilogue: OK"))
        .replace("{$INDEX_EPILOGUE_ERROR}", QCoreApplication::translate("FilePanel", "Epilogue: Error"))
        .replace("{$DATA_EPILOGUE_OK}", QCoreApplication::translate("FilePanel", "Epilogue: OK"))
        .replace("{$DATA_EPILOGUE_ERROR}", QCoreApplication::translate("FilePanel", "Epilogue: Error"))
        .replace("{$TRACKLIST_OFFSET}", QCoreApplication::translate("FilePanel", "Track List Offset"))
        .replace("{$TRACK_OFFSET}", QCoreApplication::translate("FilePanel", "Track Offset"))
        .replace("{$TRACK_SIZE}", QCoreApplication::translate("FilePanel", "Track Size"))
        .replace("{$HEADER}", QCoreApplication::translate("FilePanel", "Header"))
        .replace("{$SIGNATURE}", QCoreApplication::translate("FilePanel", "Signature"))
        .replace("{$NO_SIGNATURE}", QCoreApplication::translate("FilePanel", "No known signature found, aborting"))
        .replace("{$FORMAT_REVISION}", QCoreApplication::translate("FilePanel", "Format revision"))
        .replace("{$SIDE}", QCoreApplication::translate("FilePanel", "Side"))
        .replace("{$CUSTOM_DATA}", QCoreApplication::translate("FilePanel", "Custom Data"))
        .replace("{$VTOC_FOUND}", QCoreApplication::translate("FilePanel", "DOS 3.3 VTOC found"))
        .replace("{$VTOC_NOT_FOUND}", QCoreApplication::translate("FilePanel", "DOS 3.3 VTOC not found"))
        .replace("{$VTOC_CATALOG_TRACK}", QCoreApplication::translate("FilePanel", "Root Catalog Track"))
        .replace("{$VTOC_CATALOG_SECTOR}", QCoreApplication::translate("FilePanel", "Root Catalog Sector"))
        .replace("{$VTOC_DOS_RELEASE}", QCoreApplication::translate("FilePanel", "DOS Release"))
        .replace("{$VTOC_VOLUME_ID}", QCoreApplication::translate("FilePanel", "Volume ID"))
        .replace("{$VTOC_VOLUME_NAME}", QCoreApplication::translate("FilePanel", "Volume name"))
        .replace("{$VTOC_PAIRS_ON_SECTOR}", QCoreApplication::translate("FilePanel", "Pairs per T/S list"))
        .replace("{$VTOC_LAST_TRACK}", QCoreApplication::translate("FilePanel", "Last track"))
        .replace("{$VTOC_DIRECTION}", QCoreApplication::translate("FilePanel", "Direction"))
        .replace("{$VTOC_TRACKS_TOTAL}", QCoreApplication::translate("FilePanel", "Tracks total"))
        .replace("{$VTOC_SECTORS_ON_TRACK}", QCoreApplication::translate("FilePanel", "Sectors on track"))
        .replace("{$VTOC_BYTES_PER_SECTOR}", QCoreApplication::translate("FilePanel", "Bytes per sector"))
        .replace("{$ERROR_OPENING}", QCoreApplication::translate("FilePanel", "Error opening the file"))
        .replace("{$ERROR_LOADING}", QCoreApplication::translate("FilePanel", "Error loading, check if the file type is correct"))
        .replace("{$DPB_INFO}", QCoreApplication::translate("FilePanel", "DPB Information"))
        .replace("{$DPB_VOLUME_ID}", QCoreApplication::translate("FilePanel", "Volume ID"))
        .replace("{$DPB_TYPE}", QCoreApplication::translate("FilePanel", "Device type"))
        .replace("{$DPB_DSIDE}", QCoreApplication::translate("FilePanel", "DSIDE"))
        .replace("{$DPB_TSIZE}", QCoreApplication::translate("FilePanel", "Blocks on track"))
        .replace("{$DPB_DSIZE}", QCoreApplication::translate("FilePanel", "Tracks on disk"))
        .replace("{$DPB_MAXBLOK}", QCoreApplication::translate("FilePanel", "Last block"))
        .replace("{$DPB_VTOCADR}", QCoreApplication::translate("FilePanel", "VTOC block"))
        .replace("{$EXTENT}", QCoreApplication::translate("FilePanel", "Extent"))
        .replace("{$FREE_SECTORS}", QCoreApplication::translate("FilePanel", "Free sectors"))
        .replace("{$FREE_BYTES}", QCoreApplication::translate("FilePanel", "Free bytes"))
        .replace("{$META_FILENAME}", QCoreApplication::translate("FilePanel", "File Name"))
        .replace("{$META_PROTECTED}", QCoreApplication::translate("FilePanel", "Protected"))
        .replace("{$META_TYPE}", QCoreApplication::translate("FilePanel", "Type"))
        .replace("{$META_EXTENDED}", QCoreApplication::translate("FilePanel", "Extended"))
        .replace("{$AGAT_VR_FOUND}", QCoreApplication::translate("FilePanel", "Agat image VR block found"))
        .replace("{$AGAT_VR_MODE}", QCoreApplication::translate("FilePanel", "Video mode"))
        .replace("{$AGAT_VR_AGAT_GMODES}", QCoreApplication::translate("FilePanel", "Agat graphic"))
        .replace("{$AGAT_VR_AGAT_TMODES}", QCoreApplication::translate("FilePanel", "Agat text"))
        .replace("{$AGAT_VR_A2_MODES}", QCoreApplication::translate("FilePanel", "Apple II modes"))
        .replace("{$AGAT_VR_GIGA_MODES}", QCoreApplication::translate("FilePanel", "Agat GigaScreen"))
        .replace("{$AGAT_VR_MAIN_PALETTE}", QCoreApplication::translate("FilePanel", "Main palette"))
        .replace("{$AGAT_VR_ATL_PALETTE}", QCoreApplication::translate("FilePanel", "Alternative palette"))
        .replace("{$AGAT_VR_CUSTOM_PALETTE}", QCoreApplication::translate("FilePanel", "Custom palette"))
        .replace("{$AGAT_VR_COMMENT}", QCoreApplication::translate("FilePanel", "Comment block"))
        .replace("{$AGAT_VR_FONT}", QCoreApplication::translate("FilePanel", "Font ID"))
        .replace("{$AGAT_VR_CUSTOM_FONT}", QCoreApplication::translate("FilePanel", "Custom font"))

        // 15 viewer placeholders (ViewDialog context)
        .replace("{$PALETTE}", QCoreApplication::translate("ViewDialog", "Palette"))
        .replace("{$COLOR}", QCoreApplication::translate("ViewDialog", "Color"))
        .replace("{$MONOCHROME}", QCoreApplication::translate("ViewDialog", "Monochrome"))
        .replace("{$CUSTOM_PALETTE}", QCoreApplication::translate("ViewDialog", "Custom palette"))
        .replace("{$BW}", QCoreApplication::translate("ViewDialog", "b/w"))
        .replace("{$FONT_LOADING_ERROR}", QCoreApplication::translate("ViewDialog", "Custom font loading error"))
        .replace("{$NTSC_AGAT_IMPROVED}", QCoreApplication::translate("ViewDialog", "Agat Improved"))
        .replace("{$NTSC_APPLE_IMPROVED}", QCoreApplication::translate("ViewDialog", "Apple Improved"))
        .replace("{$NTSC_APPLE_ORIGINAL}", QCoreApplication::translate("ViewDialog", "Apple NTSC Original"))
        .replace("{$AGAT_FONT_A7_CLASSIC}", QCoreApplication::translate("ViewDialog", "Agat-7 classic font"))
        .replace("{$AGAT_FONT_A7_ENCHANCED}", QCoreApplication::translate("ViewDialog", "Agat-7 enhanced font"))
        .replace("{$AGAT_FONT_A9_CLASSIC}", QCoreApplication::translate("ViewDialog", "Agat-9 classic font"))
        .replace("{$AGAT_FONT_CUSTOM_GARNIZON}", QCoreApplication::translate("ViewDialog", "GARNIZON custom font"))
        .replace("{$AGAT_FONT_CUSTOM_LOADED}", QCoreApplication::translate("ViewDialog", "Loaded custom font"))
        .replace("{$FONT_A9}", QCoreApplication::translate("ViewDialog", "Agat-9 Font"))
        .replace("{$FONT_A7}", QCoreApplication::translate("ViewDialog", "Agat-7 Font"))
        .replace("{$FONT_FILE}", QCoreApplication::translate("ViewDialog", "Font file"))

        .replace("{$SELECTOR_AGAT_PALETTE}", QCoreApplication::translate("ViewDialog", "Palette"))
        .replace("{$SELECTOR_APPLE_HIRES_AGAT}", QCoreApplication::translate("ViewDialog", "Agat color mode"))
        .replace("{$SELECTOR_APPLE_HIRES_APPLE}", QCoreApplication::translate("ViewDialog", "Apple color mode"))
        .replace("{$SELECTOR_AGAT_FONT_TYPE}", QCoreApplication::translate("ViewDialog", "Font type"))
        .replace("{$SELECTOR_AGAT_FONT}", QCoreApplication::translate("ViewDialog", "Font"))
        ;
}