// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2025 Mikhail Revzin <p3.141592653589793238462643@gmail.com>
// Part of the DISK Commander project: https://github.com/Ptr314/dsk_commander
// Description: Text placeholder replacement utilities for UI strings

#pragma once

#include <QString>
#include <QCoreApplication>

inline QString replacePlaceholders(const QString& input)
{
    return QString(input)
        // 102 disk/filesystem placeholders (FilePanel context)
        .replace("{$DIRECTORY_ENTRY}", QCoreApplication::translate("FilePanel", "Directory Entry"))
        .replace("{$FILE_NAME}", QCoreApplication::translate("FilePanel", "File Name"))
        .replace("{$SIZE}", QCoreApplication::translate("FilePanel", "File Size"))
        .replace("{$BYTES}", QCoreApplication::translate("FilePanel", "byte(s)"))
        .replace("{$SIDES}", QCoreApplication::translate("FilePanel", "Sides"))
        .replace("{$TRACKS}", QCoreApplication::translate("FilePanel", "Tracks"))
        .replace("{$SECTORS}", QCoreApplication::translate("FilePanel", "sector(s)"))
        .replace("{$ATTRIBUTES}", QCoreApplication::translate("FilePanel", "Attributes"))
        .replace("{$DATE}", QCoreApplication::translate("FilePanel", "Date"))
        .replace("{$TYPE}", QCoreApplication::translate("FilePanel", "Type"))
        .replace("{$PROTECTED}", QCoreApplication::translate("FilePanel", "Protected"))
        .replace("{$YES}", QCoreApplication::translate("FilePanel", "Yes"))
        .replace("{$NO}", QCoreApplication::translate("FilePanel", "No"))
        .replace("{$TS_LIST_LOCATION}", QCoreApplication::translate("FilePanel", "T/S List Location"))
        .replace("{$TS_LIST_DATA}", QCoreApplication::translate("FilePanel", "T/S List Contents"))
        .replace("{$INCORRECT_TS_DATA}", QCoreApplication::translate("FilePanel", "Incorrect T/S data, stopping iterations"))
        .replace("{$NEXT_TS}", QCoreApplication::translate("FilePanel", "Next T/S List Location"))
        .replace("{$FILE_END_REACHED}", QCoreApplication::translate("FilePanel", "File End Reached"))
        .replace("{$FILE_DELETED}", QCoreApplication::translate("FilePanel", "The file is marked as deleted, the data below may be incorrect"))
        .replace("{$ERROR_PARSING}", QCoreApplication::translate("FilePanel", "File parsing error"))
        .replace("{$TRACK}", QCoreApplication::translate("FilePanel", "Track"))
        .replace("{$TRACK_SHORT}", QCoreApplication::translate("FilePanel", "T"))
        .replace("{$SIDE_SHORT}", QCoreApplication::translate("FilePanel", "H"))
        .replace("{$PHYSICAL_SECTOR}", QCoreApplication::translate("FilePanel", "S"))
        .replace("{$LOGICAL_SECTOR}", QCoreApplication::translate("FilePanel", "S"))
        .replace("{$PARSING_FINISHED}", QCoreApplication::translate("FilePanel", "Parsing finished"))
        .replace("{$VOLUME_ID}", QCoreApplication::translate("FilePanel", "V"))
        .replace("{$SECTOR_INDEX}", QCoreApplication::translate("FilePanel", "Index"))
        .replace("{$INDEX_MARK}", QCoreApplication::translate("FilePanel", "Index Mark"))
        .replace("{$DATA_MARK}", QCoreApplication::translate("FilePanel", "Data Mark"))
        .replace("{$DATA_FIELD}", QCoreApplication::translate("FilePanel", "Sector Data"))
        .replace("{$SECTOR_INDEX_END_OK}", QCoreApplication::translate("FilePanel", "End Mark: OK"))
        .replace("{$SECTOR_INDEX_END_ERROR}", QCoreApplication::translate("FilePanel", "End Mark: Not Detected"))
        .replace("{$SECTOR_CRC_OK}", QCoreApplication::translate("FilePanel", "CRC: OK"))
        .replace("{$SECTOR_CRC_ERROR}", QCoreApplication::translate("FilePanel", "CRC: Error"))
        .replace("{$CRC_EXPECTED}", QCoreApplication::translate("FilePanel", "Expected"))
        .replace("{$CRC_FOUND}", QCoreApplication::translate("FilePanel", "Found"))
        .replace("{$SECTOR_ERROR}", QCoreApplication::translate("FilePanel", "Data Error"))
        .replace("{$INDEX_CRC_OK}", QCoreApplication::translate("FilePanel", "CRC: OK"))
        .replace("{$INDEX_CRC_ERROR}", QCoreApplication::translate("FilePanel", "CRC: Error"))
        .replace("{$INDEX_EPILOGUE_OK}", QCoreApplication::translate("FilePanel", "Epilogue: OK"))
        .replace("{$INDEX_EPILOGUE_ERROR}", QCoreApplication::translate("FilePanel", "Epilogue: Error"))
        .replace("{$DATA_EPILOGUE_OK}", QCoreApplication::translate("FilePanel", "Epilogue: OK"))
        .replace("{$DATA_EPILOGUE_ERROR}", QCoreApplication::translate("FilePanel", "Epilogue: Error"))
        .replace("{$TRACKLIST_OFFSET}", QCoreApplication::translate("FilePanel", "Track List Offset"))
        .replace("{$TRACK_OFFSET}", QCoreApplication::translate("FilePanel", "Track Offset"))
        .replace("{$TRACK_SIZE}", QCoreApplication::translate("FilePanel", "Track Size"))
        .replace("{$HEADER}", QCoreApplication::translate("FilePanel", "Header"))
        .replace("{$SIGNATURE}", QCoreApplication::translate("FilePanel", "Signature"))
        .replace("{$NO_SIGNATURE}", QCoreApplication::translate("FilePanel", "No known signature found, aborting"))
        .replace("{$FORMAT_REVISION}", QCoreApplication::translate("FilePanel", "Format revision"))
        .replace("{$SIDE}", QCoreApplication::translate("FilePanel", "Side"))
        .replace("{$CUSTOM_DATA}", QCoreApplication::translate("FilePanel", "Custom Data"))
        .replace("{$VTOC_FOUND}", QCoreApplication::translate("FilePanel", "DOS 3.3 VTOC found"))
        .replace("{$VTOC_NOT_FOUND}", QCoreApplication::translate("FilePanel", "DOS 3.3 VTOC not found"))
        .replace("{$VTOC_CATALOG_TRACK}", QCoreApplication::translate("FilePanel", "Root Catalog Track"))
        .replace("{$VTOC_CATALOG_SECTOR}", QCoreApplication::translate("FilePanel", "Root Catalog Sector"))
        .replace("{$VTOC_DOS_RELEASE}", QCoreApplication::translate("FilePanel", "DOS Release"))
        .replace("{$VTOC_VOLUME_ID}", QCoreApplication::translate("FilePanel", "Volume ID"))
        .replace("{$VTOC_VOLUME_NAME}", QCoreApplication::translate("FilePanel", "Volume name"))
        .replace("{$VTOC_PAIRS_ON_SECTOR}", QCoreApplication::translate("FilePanel", "Pairs per T/S list"))
        .replace("{$VTOC_LAST_TRACK}", QCoreApplication::translate("FilePanel", "Last track"))
        .replace("{$VTOC_DIRECTION}", QCoreApplication::translate("FilePanel", "Direction"))
        .replace("{$VTOC_TRACKS_TOTAL}", QCoreApplication::translate("FilePanel", "Tracks total"))
        .replace("{$VTOC_SECTORS_ON_TRACK}", QCoreApplication::translate("FilePanel", "Sectors on track"))
        .replace("{$VTOC_BYTES_PER_SECTOR}", QCoreApplication::translate("FilePanel", "Bytes per sector"))
        .replace("{$ERROR_OPENING}", QCoreApplication::translate("FilePanel", "Error opening the file"))
        .replace("{$ERROR_LOADING}", QCoreApplication::translate("FilePanel", "Error loading, check if the file type is correct"))
        .replace("{$DPB_INFO}", QCoreApplication::translate("FilePanel", "DPB Information"))
        .replace("{$DPB_VOLUME_ID}", QCoreApplication::translate("FilePanel", "Volume ID"))
        .replace("{$DPB_TYPE}", QCoreApplication::translate("FilePanel", "Device type"))
        .replace("{$DPB_DSIDE}", QCoreApplication::translate("FilePanel", "DSIDE"))
        .replace("{$DPB_TSIZE}", QCoreApplication::translate("FilePanel", "Blocks on track"))
        .replace("{$DPB_DSIZE}", QCoreApplication::translate("FilePanel", "Tracks on disk"))
        .replace("{$DPB_MAXBLOK}", QCoreApplication::translate("FilePanel", "Last block"))
        .replace("{$DPB_VTOCADR}", QCoreApplication::translate("FilePanel", "VTOC block"))
        .replace("{$EXTENT}", QCoreApplication::translate("FilePanel", "Extent"))
        .replace("{$FREE_SECTORS}", QCoreApplication::translate("FilePanel", "Free sectors"))
        .replace("{$FREE_BYTES}", QCoreApplication::translate("FilePanel", "Free bytes"))
        .replace("{$META_FILENAME}", QCoreApplication::translate("FilePanel", "File Name"))
        .replace("{$META_PROTECTED}", QCoreApplication::translate("FilePanel", "Protected"))
        .replace("{$META_TYPE}", QCoreApplication::translate("FilePanel", "Type"))
        .replace("{$META_EXTENDED}", QCoreApplication::translate("FilePanel", "Extended"))
        .replace("{$AGAT_VR_FOUND}", QCoreApplication::translate("FilePanel", "Agat image VR block found"))
        .replace("{$AGAT_VR_MODE}", QCoreApplication::translate("FilePanel", "Video mode"))
        .replace("{$AGAT_VR_AGAT_GMODES}", QCoreApplication::translate("FilePanel", "Agat graphic"))
        .replace("{$AGAT_VR_AGAT_TMODES}", QCoreApplication::translate("FilePanel", "Agat text"))
        .replace("{$AGAT_VR_A2_MODES}", QCoreApplication::translate("FilePanel", "Apple II modes"))
        .replace("{$AGAT_VR_GIGA_MODES}", QCoreApplication::translate("FilePanel", "Agat GigaScreen"))
        .replace("{$AGAT_VR_MAIN_PALETTE}", QCoreApplication::translate("FilePanel", "Main palette"))
        .replace("{$AGAT_VR_ATL_PALETTE}", QCoreApplication::translate("FilePanel", "Alternative palette"))
        .replace("{$AGAT_VR_CUSTOM_PALETTE}", QCoreApplication::translate("FilePanel", "Custom palette"))
        .replace("{$AGAT_VR_COMMENT}", QCoreApplication::translate("FilePanel", "Comment block"))
        .replace("{$AGAT_VR_FONT}", QCoreApplication::translate("FilePanel", "Font ID"))
        .replace("{$AGAT_VR_CUSTOM_FONT}", QCoreApplication::translate("FilePanel", "Custom font"))
        .replace("{$COMMENT}", QCoreApplication::translate("FilePanel", "Comment"))
        .replace("{$SECTORS_MAP}", QCoreApplication::translate("FilePanel", "Sector map"))
        .replace("{$CYLINDERS_MAP}", QCoreApplication::translate("FilePanel", "Cylinder map"))
        .replace("{$HEAD_MAP}", QCoreApplication::translate("FilePanel", "Head map"))
        .replace("{$UNEXPECTED_END_OF_FILE}", QCoreApplication::translate("FilePanel", "Error: Unexpected end of file"))
        .replace("{$SECTOR_UNAVAILABLE}", QCoreApplication::translate("FilePanel", "Unavailable sector"))
        .replace("{$NORMAL_DATA}", QCoreApplication::translate("FilePanel", "Normal data"))
        .replace("{$DATA_COMPRESSED}", QCoreApplication::translate("FilePanel", "Compressed"))
        .replace("{$DATA_DELETED}", QCoreApplication::translate("FilePanel", "Deleted"))
        .replace("{$NORMAL_DATA_WITH_ERROR}", QCoreApplication::translate("FilePanel", "DATA ERROR"))
        .replace("{$UNKNOWN_DATA_MARKER}", QCoreApplication::translate("FilePanel", "Unknown data marker"))
        .replace("{$FILE_HAS_ERRORS}", QCoreApplication::translate("FilePanel", "The file contains corrupted data!"))
        .replace("{$FILE_HAS_NO_ERRORS}", QCoreApplication::translate("FilePanel", "The file was read without errors."))

        // CP/M related strings
        .replace("{$CPM_SECTOR_SIZE}", QCoreApplication::translate("FilePanel", "Sector size"))
        .replace("{$CPM_BLOCK_SIZE}", QCoreApplication::translate("FilePanel", "Block size"))
        .replace("{$CPM_SECTORS_PER_BLOCK}", QCoreApplication::translate("FilePanel", "Sectors per block"))
        .replace("{$CPM_RESERVED_TRACKS}", QCoreApplication::translate("FilePanel", "Reserved tracks"))
        .replace("{$CPM_BLOCK}", QCoreApplication::translate("FilePanel", "Block"))
        .replace("{$CPM_SECTORS}", QCoreApplication::translate("FilePanel", "Sectors"))
        .replace("{$CPM_SECTORS_PER_TRACK}", QCoreApplication::translate("FilePanel", "Sectors per track"))
        .replace("{$CPM_TOTAL_BLOCKS}", QCoreApplication::translate("FilePanel", "Total blocks"))
        .replace("{$CPM_DIR_ENTRIES}", QCoreApplication::translate("FilePanel", "Directory entries"))
        .replace("{$DISK_HAS_BAD_SECTORS}", QCoreApplication::translate("FilePanel", "The disk contains bad sectors!"))
        .replace("{$BAD_SECTOR_IN_RESERVED}", QCoreApplication::translate("FilePanel", "Bad sector in reserved track"))
        .replace("{$NO_BAD_SECTORS_IN_RESERVED}", QCoreApplication::translate("FilePanel", "No bad sectors in reserved tracks"))
        .replace("{$BAD_SECTOR_IN_DIRECTORY}", QCoreApplication::translate("FilePanel", "Bad sector in directory"))
        .replace("{$NO_BAD_SECTORS_IN_DIRECTORY}", QCoreApplication::translate("FilePanel", "No bad sectors in directory"))
        .replace("{$FILE_HAS_BAD_SECTORS}", QCoreApplication::translate("FilePanel", "File has bad sectors"))
        .replace("{$NO_FILES_WITH_BAD_SECTORS}", QCoreApplication::translate("FilePanel", "No files with bad sectors"))
        .replace("{$META_CPM_USER}", QCoreApplication::translate("FilePanel", "User number"))
        .replace("{$META_CPM_SYSTEM}", QCoreApplication::translate("FilePanel", "System"))
        .replace("{$META_CPM_ARCHIVE}", QCoreApplication::translate("FilePanel", "Archive"))

        // FAT related strings
        .replace("{$FAT_FS_TYPE}", QCoreApplication::translate("FilePanel", "Filesystem type"))
        .replace("{$FAT_OEM_NAME}", QCoreApplication::translate("FilePanel", "OEM name"))
        .replace("{$FAT_MEDIA_DESCRIPTOR}", QCoreApplication::translate("FilePanel", "Media descriptor"))
        .replace("{$FAT_BPB_GEOMETRY}", QCoreApplication::translate("FilePanel", "BPB geometry"))
        .replace("{$FAT_BYTES_PER_SECTOR}", QCoreApplication::translate("FilePanel", "Bytes per sector"))
        .replace("{$FAT_SECTORS_PER_CLUSTER}", QCoreApplication::translate("FilePanel", "Sectors per cluster"))
        .replace("{$FAT_CLUSTER_SIZE}", QCoreApplication::translate("FilePanel", "Cluster size"))
        .replace("{$FAT_SECTORS_PER_TRACK}", QCoreApplication::translate("FilePanel", "Sectors per track (FAT)"))
        .replace("{$FAT_NUM_HEADS}", QCoreApplication::translate("FilePanel", "Number of heads"))
        .replace("{$FAT_TOTAL_SECTORS}", QCoreApplication::translate("FilePanel", "Total sectors"))
        .replace("{$FAT_HIDDEN_SECTORS}", QCoreApplication::translate("FilePanel", "Hidden sectors"))
        .replace("{$FAT_LAYOUT}", QCoreApplication::translate("FilePanel", "Volume layout"))
        .replace("{$FAT_RESERVED_SECTORS}", QCoreApplication::translate("FilePanel", "Reserved sectors"))
        .replace("{$FAT_NUM_FATS}", QCoreApplication::translate("FilePanel", "Number of FATs"))
        .replace("{$FAT_SECTORS_PER_FAT}", QCoreApplication::translate("FilePanel", "Sectors per FAT"))
        .replace("{$FAT_ROOT_ENTRIES}", QCoreApplication::translate("FilePanel", "Root directory entries"))
        .replace("{$FAT_ROOT_DIR_SECTORS}", QCoreApplication::translate("FilePanel", "Root directory sectors"))
        .replace("{$FAT_REGIONS_LBA}", QCoreApplication::translate("FilePanel", "Region LBAs"))
        .replace("{$FAT_FAT_START}", QCoreApplication::translate("FilePanel", "FAT start LBA"))
        .replace("{$FAT_ROOT_DIR_START}", QCoreApplication::translate("FilePanel", "Root directory start LBA"))
        .replace("{$FAT_DATA_START}", QCoreApplication::translate("FilePanel", "Data region start LBA"))
        .replace("{$FAT_CLUSTERS}", QCoreApplication::translate("FilePanel", "Cluster usage"))
        .replace("{$FAT_TOTAL_CLUSTERS}", QCoreApplication::translate("FilePanel", "Total clusters"))
        .replace("{$FAT_USED_CLUSTERS}", QCoreApplication::translate("FilePanel", "Used clusters"))
        .replace("{$FAT_FREE_CLUSTERS}", QCoreApplication::translate("FilePanel", "Free clusters"))
        .replace("{$FAT_BAD_CLUSTERS}", QCoreApplication::translate("FilePanel", "Bad clusters"))

        // ProDOS related strings
        .replace("{$PRODOS_VOLUME_NAME}", QCoreApplication::translate("FilePanel", "Volume name"))
        .replace("{$PRODOS_CREATED}", QCoreApplication::translate("FilePanel", "Created"))
        .replace("{$PRODOS_MODIFIED}", QCoreApplication::translate("FilePanel", "Last modified"))
        .replace("{$PRODOS_VERSION}", QCoreApplication::translate("FilePanel", "Version"))
        .replace("{$PRODOS_MIN_VERSION}", QCoreApplication::translate("FilePanel", "Minimum version"))
        .replace("{$PRODOS_ACCESS}", QCoreApplication::translate("FilePanel", "Access"))
        .replace("{$PRODOS_LAYOUT}", QCoreApplication::translate("FilePanel", "Volume layout"))
        .replace("{$PRODOS_BLOCK_SIZE}", QCoreApplication::translate("FilePanel", "Block size"))
        .replace("{$PRODOS_TOTAL_BLOCKS}", QCoreApplication::translate("FilePanel", "Total blocks"))
        .replace("{$PRODOS_USED_BLOCKS}", QCoreApplication::translate("FilePanel", "Used blocks"))
        .replace("{$PRODOS_FREE_BLOCKS}", QCoreApplication::translate("FilePanel", "Free blocks"))
        .replace("{$PRODOS_BITMAP_POINTER}", QCoreApplication::translate("FilePanel", "Bitmap first block"))
        .replace("{$PRODOS_DIRECTORY}", QCoreApplication::translate("FilePanel", "Volume directory"))
        .replace("{$PRODOS_FILE_COUNT}", QCoreApplication::translate("FilePanel", "Files in the root directory"))
        .replace("{$PRODOS_ENTRY_LENGTH}", QCoreApplication::translate("FilePanel", "Directory entry length"))
        .replace("{$PRODOS_ENTRIES_PER_BLOCK}", QCoreApplication::translate("FilePanel", "Directory entries per block"))
        .replace("{$PRODOS_STORAGE_TYPE}", QCoreApplication::translate("FilePanel", "Storage type"))
        .replace("{$PRODOS_BLOCKS_USED}", QCoreApplication::translate("FilePanel", "Blocks used"))
        .replace("{$PRODOS_KEY_POINTER}", QCoreApplication::translate("FilePanel", "Key block"))
        .replace("{$PRODOS_AUX_TYPE}", QCoreApplication::translate("FilePanel", "Auxiliary type"))
        .replace("{$PRODOS_FILE_BLOCKS}", QCoreApplication::translate("FilePanel", "File blocks"))
        .replace("{$NO_DATE}", QCoreApplication::translate("FilePanel", "no date"))

        // Onix related strings
        .replace("{$ONIX_LAYOUT}", QCoreApplication::translate("FilePanel", "Volume layout"))
        .replace("{$ONIX_BLOCK_SIZE}", QCoreApplication::translate("FilePanel", "Block size"))
        .replace("{$ONIX_DISK_BLOCKS}", QCoreApplication::translate("FilePanel", "Blocks on the disk"))
        .replace("{$ONIX_DESCRIBED_BLOCKS}", QCoreApplication::translate("FilePanel", "Blocks in the allocation table"))
        .replace("{$ONIX_SYSTEM_BLOCKS}", QCoreApplication::translate("FilePanel", "System blocks"))
        .replace("{$ONIX_USED_BLOCKS}", QCoreApplication::translate("FilePanel", "Used blocks"))
        .replace("{$ONIX_FREE_BLOCKS}", QCoreApplication::translate("FilePanel", "Free blocks"))
        .replace("{$ONIX_ALLOCATION_TABLE}", QCoreApplication::translate("FilePanel", "Allocation table"))
        .replace("{$ONIX_TABLE_FIRST_BLOCK}", QCoreApplication::translate("FilePanel", "Table first block"))
        .replace("{$ONIX_TABLE_BLOCKS}", QCoreApplication::translate("FilePanel", "Table blocks"))
        .replace("{$ONIX_ROOT_BLOCK}", QCoreApplication::translate("FilePanel", "Root directory block"))
        .replace("{$ONIX_DIRECTORY}", QCoreApplication::translate("FilePanel", "Directory"))
        .replace("{$ONIX_ENTRY_LENGTH}", QCoreApplication::translate("FilePanel", "Directory entry length"))
        .replace("{$ONIX_ENTRIES_PER_BLOCK}", QCoreApplication::translate("FilePanel", "Directory entries per block"))
        .replace("{$ONIX_ATTRIBUTES}", QCoreApplication::translate("FilePanel", "Attributes"))
        .replace("{$ONIX_DATE}", QCoreApplication::translate("FilePanel", "Date"))
        .replace("{$ONIX_FIRST_BLOCK}", QCoreApplication::translate("FilePanel", "First block"))
        .replace("{$ONIX_LOAD_ADDRESS}", QCoreApplication::translate("FilePanel", "Load address"))
        .replace("{$ONIX_EXEC_ADDRESS}", QCoreApplication::translate("FilePanel", "Execution address"))
        .replace("{$ONIX_FILE_BLOCKS}", QCoreApplication::translate("FilePanel", "File blocks"))

        // 15 viewer placeholders (ViewDialog context)
        .replace("{$PALETTE}", QCoreApplication::translate("ViewDialog", "Palette"))
        .replace("{$COLOR}", QCoreApplication::translate("ViewDialog", "Color"))
        .replace("{$MONOCHROME}", QCoreApplication::translate("ViewDialog", "Monochrome"))
        .replace("{$CUSTOM_PALETTE}", QCoreApplication::translate("ViewDialog", "Custom palette"))
        .replace("{$BW}", QCoreApplication::translate("ViewDialog", "b/w"))
        .replace("{$FONT_LOADING_ERROR}", QCoreApplication::translate("ViewDialog", "Custom font loading error"))
        .replace("{$NTSC_AGAT_IMPROVED}", QCoreApplication::translate("ViewDialog", "Agat Improved"))
        .replace("{$NTSC_APPLE_IMPROVED}", QCoreApplication::translate("ViewDialog", "Apple Improved"))
        .replace("{$NTSC_APPLE_ORIGINAL}", QCoreApplication::translate("ViewDialog", "Apple NTSC Original"))
        .replace("{$AGAT_FONT_A7_CLASSIC}", QCoreApplication::translate("ViewDialog", "Agat-7 classic font"))
        .replace("{$AGAT_FONT_A7_ENCHANCED}", QCoreApplication::translate("ViewDialog", "Agat-7 enhanced font"))
        .replace("{$AGAT_FONT_A9_CLASSIC}", QCoreApplication::translate("ViewDialog", "Agat-9 classic font"))
        .replace("{$AGAT_FONT_CUSTOM_GARNIZON}", QCoreApplication::translate("ViewDialog", "GARNIZON custom font"))
        .replace("{$AGAT_FONT_CUSTOM_LOADED}", QCoreApplication::translate("ViewDialog", "Loaded custom font"))
        .replace("{$FONT_A9}", QCoreApplication::translate("ViewDialog", "Agat-9 Font"))
        .replace("{$FONT_A7}", QCoreApplication::translate("ViewDialog", "Agat-7 Font"))
        .replace("{$FONT_FILE}", QCoreApplication::translate("ViewDialog", "Font file"))
        .replace("{$FONT_FILE_BFT}", QCoreApplication::translate("ViewDialog", "BFT Font"))

        .replace("{$SELECTOR_AGAT_PALETTE}", QCoreApplication::translate("ViewDialog", "Palette"))
        .replace("{$SELECTOR_AGAT_INFO}", QCoreApplication::translate("ViewDialog", "Comment"))
        .replace("{$SELECTOR_APPLE_HIRES_AGAT}", QCoreApplication::translate("ViewDialog", "Agat color mode"))
        .replace("{$SELECTOR_APPLE_HIRES_APPLE}", QCoreApplication::translate("ViewDialog", "Apple color mode"))
        .replace("{$SELECTOR_AGAT_FONT_TYPE}", QCoreApplication::translate("ViewDialog", "Font type"))
        .replace("{$SELECTOR_AGAT_FONT}", QCoreApplication::translate("ViewDialog", "Font"))
        ;
}